drop table if exists coupons cascade;
drop table if exists env_properties cascade;
drop table if exists parcel_package cascade;
drop table if exists vehicles cascade;

create table env_properties (
    id integer generated by default as identity,
    env_key varchar(255),
    env_value varchar(255),
    description varchar(255),
    state tinyint check (state between 0 and 1),
    primary key (id)
);
insert into env_properties (description, env_key, env_value, state) values
('Base Fare For Parcel', 'PARCEL_BASE_FARE', '100', 1),
('No Of Vehicles', 'VEHICLE_COUNT', '3', 0);

create table coupons (
    id integer generated by default as identity,
    coupoun_name varchar(255),
    discount float(53),
    min_distance float(53),
    max_distance float(53),
    min_weight float(53),
    max_weight float(53),
    primary key (id)
);
insert into coupons(coupoun_name,discount,min_distance,max_distance,min_weight,max_weight) values
('OFR001',10,0,200,70,200),
('OFR002',7, 50,150,100,250),
('OFR003',5, 50,250,10,150);

create table vehicles (
        id integer generated by default as identity,
        vehicle_name varchar(30),
        driver_name varchar(30),
        
        speed float(53),
        max_wt_limit float(53),
        status varchar(225),
        available_time timestamp(6),
        primary key (id)
);
insert into vehicles (vehicle_name, driver_name, speed, max_wt_limit, status) values 
('KA-41-EF-8771','Jagadish',70,200,'AVAILABLE'),
('JP-41-EF-1212','Sarita',70,200,'AVAILABLE'),
('JP-41-EF-1213','Suman',70,200,'AVAILABLE'),
('JP-41-EF-1214','Sateesh',70,200,'AVAILABLE');

create table parcel_package (
	id integer generated by default as identity,
	package_name varchar(255),
	copoun_code varchar(255),
	weight float(53),
	distance float(53),

    discount_percent float(53),
    discount_amount float(53),
    no_discout_package_cost float(53),
    
    start_delivery_time timestamp(6),
    delivery_minutes integer,
    end_delivery_time timestamp(6),
    
    status varchar(255),
    mapped_vehicle varchar(30),
    
    primary key (id)
);
insert into
    parcel_package
    (copoun_code, discount_amount, discount_percent, distance, end_delivery_time, no_discout_package_cost, package_name, start_delivery_time, status, weight, mapped_vehicle) 
values
    ('OFR001', 0.0, 0.0, 5.0, '2025-10-12 00:00:00', 175.0, 'PKG001', '2025-10-12 00:00:00', 'READY', 5.0, null),
	('OFR002', 0.0, 0.0, 5.0, '2025-10-12 00:00:00', 275.0, 'PKG002', '2025-10-12 00:00:00', 'READY', 15.0, null),
	('OFR003', 35.0, 5.0, 100.0, '2025-10-12 00:00:00', 700.0, 'PKG003', '2025-10-12 00:00:00', 'READY', 10.0, null);

